#!/usr/bin/env bash

sudo apt-get install -y build-essential
sudo apt-get install -y libssl-dev libreadline-dev
sudo apt-get install -y zlib1g-dev

asdf plugin-add ruby
asdf install ruby 2.5.3
asdf global ruby 2.5.3

gem install bundler -v '~> 1.0'
