#!/usr/bin/env bash

sudo apt-get install -y build-essential
sudo apt-get install -y libssl-dev libreadline-dev
sudo apt-get install -y zlib1g-dev

asdf plugin-add ruby
asdf install ruby 3.0.0
asdf global ruby 3.0.0

gem install bundler -v '~> 1.0'
gem install rubocop
gem install reek
gem install solargraph
