#!/usr/bin/env bash

set -e

sudo apt install kitty

rm -rf ~/.config/kitty/kitty-themes
git clone --depth 1 git@github.com:dexpota/kitty-themes.git ~/.config/kitty/kitty-themes

DIR=$(dirname "$(readlink -f "$0")")

mkdir -p /home/$USER/.config/kitty
rm ~/.config/kitty/kitty.conf
ln -s $DIR/kitty.conf ~/.config/kitty/kitty.conf

cd ~/.config/kitty
rm ~/.config/kitty/theme.conf
ln -s ./kitty-themes/themes/Dracula.conf ~/.config/kitty/theme.conf
