#!/usr/bin/env ruby

require_relative '../shared/system'

puts "What's your name?"
name = gets.chomp
puts "What's your email?"
email = gets.chomp

system! 'git config --global color.ui true'
system! "git config --global user.name '#{name}'"
system! "git config --global user.email '#{email}'"

unless File.exist? "#{ENV['HOME']}/.ssh/id_rsa"
  system! "ssh-keygen -t rsa -b 4096 -C '#{email}'"
end

system! "git config --global core.excludesfile '~/.gitignore'"

system! "echo 'tags' >> ~/.gitignore"

system! 'git config --global alias.adog "log --graph --abbrev-commit --decorate --date=relative --all"'
system! 'git config --global alias.lg "log --graph --pretty=format:\'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset\' --abbrev-commit"'
