#!/usr/bin/env python3

import os

os.system('sudo apt-get install linux-headers-$(uname -r) build-essential')
os.system('sudo apt-get install libreadline-dev')
os.system('asdf plugin-add postgres')
os.system('asdf install postgres 9.6.11')
os.system('asdf global postgres 9.6.11')

print('Creating a role for you on postgres')

print("\n" * 5)
print("=" * 10)

print('Role: ')
role = input()
print('Password: ')
password = input()

print('=' * 10)
print("\n" * 5)

os.system('pg_ctl start')

os.system('createuser #{role} -s')

os.system("""
    psql postgres -c "ALTER USER %s WITH PASSWORD '%s';"
""" % (role, password))

# Clear the user password from history
os.system('[ -f ~/.psql_history ] && rm ~/.psql_history')
