#!/bin/bash
info "Installing dependencies..."
apt-get install git-core \
                curl \
                zlib1g-dev \
                build-essential \
                libssl-dev \
                libreadline-dev \
                libyaml-dev \
                libsqlite3-dev \
                sqlite3 \
                libxml2-dev \
                libxslt1-dev \
                libcurl4-openssl-dev \
                software-properties-common \
                libffi-dev \
                nodejs \
                yarn

apt install -y build-essentials
apt-get install -y zlib1g-dev
success "Done!"
