#!/bin/bash
# This script is not ready. For now, it may be used to remind me what to
# install.

# Variables.
export NAME="Caio Ergos"
export EMAIL=caioergos@gmail.com

info "Type your password"
read PASSWORD

. ./logger
. ./postinstall/_dependencies
. ./postinstall/_zsh
. ./postinstall/_asdf

info "Installing Node..."
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt install -y node
success "Done!"

info "Installing Yarn..."
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt install -y yarn
end

info "Installing Git..."
apt install -y git
git config --global color.ui true
git config --global user.name $NAME
git config --global user.email $EMAIL
ssh-keygen -t rsa -b 4096 -C $EMAIL
success "Done!"

# Get my SSH pub key.
info "This is your ssh key."
success $(cat ~/.ssh/id_rsa.pub)

info "Installing Vundle..."
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
success "Done!"

info "Installing Curl..."
apt install -y curl
success "Done!"

info "Installing Docker..."
sudo apt-get remove docker docker-engine docker.io
apt-get update
apt-get install \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
apt-get update
apt-get install docker-ce
success "Done!"


