#!/usr/bin/env ruby

require 'fileutils'

HOME_DIR = ENV['HOME']

system('sudo add-apt-repository ppa:linuxuprising/shutter')
system('sudo apt update')
system('sudo apt install -y i3 pavucontrol xbacklight playerctl mc shutter synapse')

FileUtils.cd File.dirname(__FILE__) do
  FileUtils.mkdir_p(File.expand_path('./.config/i3', HOME_DIR))
  FileUtils.cp 'config', "#{HOME_DIR}/.config/i3/config"
end

system('notify-send "i3" "Finished setting up i3"')
