#!/usr/bin/env bash

set -e

export CONFIG_FILE=/usr/lib/systemd/system/keychron.service

sudo tee -a $CONFIG_FILE > /dev/null << EOF
[Unit]
Description=The command to make the Keychron K2's function keys work

[Service]
Type=oneshot
ExecStart=/bin/bash -c "echo 2 > /sys/module/hid_apple/parameters/fnmode"

[Install]
WantedBy=multi-user.target
EOF

echo "$CONFIG_FILE written."

sudo systemctl enable keychron.service

sudo tee -a /etc/bluetooth/main.conf > /dev/null << EOF
FastConnectable = true
EOF

echo "FastConnectable is now enabled."
