#!/bin/bash

which curl || sudo apt install -y curl

asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
asdf install nodejs 12.16.2
asdf global nodejs 12.16.2

