#!/usr/bin/env python3

import os

os.system('git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.1')
os.system("echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.zshrc")
os.system("echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.zshrc")
os.system('source ~/.zshrc')

