#!/usr/bin/env bash

set -e

DIR=$(dirname "$(readlink -f "$0")")

TMUX_CONF=$DIR/.tmux.conf

sudo apt install -y tmux

rm ~/.tmux.conf
ln -s $TMUX_CONF ~/.tmux.conf

if [ -d ~/.tmux/plugins/tpm ]; then
    echo 'TMP Plugin is already installed.'
else
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

gem install tmuxinator

rm -rf ~/.tmuxinator
ln -s $DIR/tmuxinator ~/.tmuxinator
