#!/usr/bin/env python3

import os
import shutil

current_path = os.path.dirname(__file__)
tmux_conf = '%s/.tmux.conf' % current_path

os.system('sudo apt install -y tmux')

shutil.copy(tmux_conf, '/home/caio/.tmux.conf')

os.system("""
  if [ -d ~/.tmux/plugins/tpm ]; then
    echo 'TMP Plugin is already installed.'
  else
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  fi
""")
