#!/usr/bin/env ruby

require 'fileutils'

require_relative '../shared/system'

HOME_DIR = ENV['HOME']

if !`which tmux || ''`.empty?
  puts "Tmux binary found at: #{`which tmux`}"
else
  system! 'sudo apt install -y libevent-dev'
  system! 'sudo apt install -y ncurses-dev'

  FileUtils.cd File.dirname(__FILE__) do
    system! 'mkdir tmux'
    system! 'tar -C tmux -xvf tmux-2.8.tar.gz'
  end

  FileUtils.cd File.dirname(__FILE__) + '/tmux/tmux-2.8' do
    system! './configure && make'
    system! 'sudo make install'
  end

  if File.exist?(File.expand_path('./tmux', __FILE__))
    FileUtils.rm_rf(File.expand_path('./tmux', __FILE__))
  end
end

puts 'Creating .tmux.conf...'

FileUtils.cd File.dirname(__FILE__) do
  if File.exist?(File.expand_path('.tmux.conf', HOME_DIR))
    puts '.tmux.conf file already exists. Do you want it to be overrided? (Y/N)'
    answer = gets.chomp.downcase

    if answer == 'y'
      FileUtils.cp '.tmux.conf', "#{HOME_DIR}/.tmux.conf"
    end
  else
    FileUtils.cp '.tmux.conf', "#{HOME_DIR}/.tmux.conf"
  end
end

system! <<~BASH
  if [ -d ~/.tmux/plugins/tpm ]; then
    echo 'TMP Plugin is already installed.'
  else
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  fi
BASH

puts 'Done.'

