#!/usr/bin/env python3

import os
import shutil

HOME_DIR = os.environ.get('HOME')

if os.system('which zsh') == 0:
    print('ZSH binary found.')
else:
    os.system('sudo apt install -y zsh')
    print('Changing defaul terminal to ZSH')
    os.system('chsh -s $(which zsh)')

if os.system('which curl') == 0:
    os.system('sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"')
elif os.system('which wget') == 0:
    os.system('sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"')
else:
    raise 'Neither curl or wget are installed.'

print('Creating .zshrc')
shutil.copyfile('%s/.zshrc' % os.path.dirname(__file__), '%s/.zshrc' % HOME_DIR)


