#!/usr/bin/env ruby

require 'fileutils'

HOME_DIR = ENV['HOME']

if !`which nvim || ''`.empty?
  puts "Neovim binary found at: #{`which nvim`}"
else
  system 'sudo chown -R $(whoami) ~/vim'
  system 'git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim'

  if system('which apt')
    system('sudo apt-get install -y software-properties-common')
    system('sudo add-apt-repository ppa:neovim-ppa/stable')
    system('sudo apt update')
    system('sudo apt install -y neovim')
    system('sudo apt-get install -y python-dev python-pip python3-dev python3-pip')
  elsif system('which pacman')
    system('sudo pacman -S neovim')
  end
end

system 'pip2 install neovim'
system 'pip3 install neovim'

FileUtils.cd File.dirname(__FILE__) do
  FileUtils.mkdir_p(File.expand_path('./.config/nvim', HOME_DIR))
  if File.exist?(File.expand_path('./.config/nvim/init.vim', HOME_DIR))
    puts 'init.vim file already exists. Do you want it to be overrided? (Y/N)'
    answer = gets.chomp.downcase

    if answer == 'y'
      FileUtils.cp '.nvimrc', "#{HOME_DIR}/.config/nvim/init.vim"
    end
  else
    FileUtils.cp '.nvimrc', "#{HOME_DIR}/.config/nvim/init.vim"
  end
end

puts <<~MSG


  After running `PluginInstall`:

  cd ~/.vim/bundle/tern-neovim
  npm install


MSG

puts 'Done.'
