#!/usr/bin/env bash

brew install neovim

npm install -g neovim
npm install -g typescript

pip3 install neovim

DIR=$(dirname "$(readlink -f "$0")")

mkdir -p /home/$USER/.config/nvim

ln -s $DIR/init.lua ~/.config/nvim/init.lua

echo 'Done.'

nvim -c "PackerInstall"
nvim -c "PackerCompile"
nvim -c "CocInstall coc-vetur coc-json coc-tsserver coc-prettier coc-eslint"
