#!/usr/bin/env python3

import os
import shutil

current_vimrc = "~/.config/nvim/init.vim"
future_vimrc = "%s/.nvimrc" % os.path.dirname(__file__)

os.system('sudo chown -R $(whoami) ~/.vim')
os.system('git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim')
os.system('sudo apt-get install -y software-properties-common')
os.system('sudo add-apt-repository ppa:neovim-ppa/stable')
os.system('sudo apt update')
os.system('sudo apt install -y neovim')
os.system('sudo apt-get install -y python-dev python-pip python3-dev python3-pip')
os.system('sudo apt install ctags')
os.system('npm install -g neovim')
os.system('npm install -g typescript')
os.system('pip2 install neovim')
os.system('pip3 install neovim')

shutil.copyfile(future_vimrc, current_vimrc)

print('Done.')
